name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  daily-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Daily Quote Script
        run: |
          python3 daily_quote.py

      - name: Configure Git
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your-email@example.com"

      - name: Commit Changes
        run: |
          git add updates/log.txt
          git commit -m "Daily update: $(date)" || echo "Nothing to commit"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
