name: Python CI Workflow

on:
  schedule:
    - cron: "*/15 * * * *"  # Run every 15 minutes
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Optionally, install specific packages directly
          # pip install requests beautifulsoup4

      # Step 4: Run the Python script
      - name: Run Python Script
        run: python max_quotes.py  # Replace `max_quotes.py` with your actual script name

      # Step 5: Commit changes to update contributions
      - name: Commit changes
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"
          echo "Dummy update at $(date)" >> contribution_log.txt
          git add .
          git commit -m "Automated contribution commit at $(date)" || echo "No changes to commit"
          git push
