name: Python CI Workflow

on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Checkout your repository
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # If you have a requirements.txt file
          # Or install specific packages:
          # pip install requests beautifulsoup4
      - name: Run Python script
        run: python max_quotes.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Update quotes