name: Python CI Workflow

on:
  # Schedule to run every 15 minutes
  schedule:
    - cron: "*/15 * * * *"
  # Run on push to main branch
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Specify a valid Python version

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the Python script
      - name: Run Python Script
        run: |
          python your_script.py  # Replace `your_script.py` with your actual script name

      # Step 5: Add a dummy commit to the repository to update the contribution graph
      - name: Make a Commit
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"
          echo "Dummy update at $(date)" >> contribution_log.txt
          git add .
          git commit -m "Automated contribution commit at $(date)"
          git push
