name: Python CI Workflow

on:
  schedule:
    - cron: "*/15 * * * *"  # Run every 15 minutes
  push:
    branches:
      - main

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Ensure this matches your Python version

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Python Script
      - name: Run Python Script
        run: python max_quotes.py  # script name

      # Step 5: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          echo "Dummy update at $(date)" >> contribution_log.txt
          git add .
          git commit -m "Automated contribution commit at $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
