name: Commit Contribution

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

     # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Use Python 3.9 (change to another version if needed)


      # Step 3: Add a contribution log
      - name: Update Contribution Log
        run: |
          echo "Contribution made at $(date)" >> contribution_log.txt

      # Step 4: Commit and push changes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated contribution commit at $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
